version: '2.3'
services:
  ml-gpu:
    build:
      context: ./
      dockerfile: ./docker/gpu/Dockerfile
    image: machine-learning-gpu
    container_name: ${CONTAINER_NAME}
    runtime: nvidia
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ./:/home
      - ${DATA_ROOT}:/data
      # bind keras application weights
      - ./.keras/:/home/penguin/.keras
      # share kaggle features
      - ~/.kaggle/:/home/penguin/.kaggle
    environment:
     # root のホームディレクトリに python の path を通すことで
     # プロジェクトルートに配置した自作のモジュールを import できるようにしている
     - PYTHONPATH=/home/
    env_file: .env
